# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "main-prod-dvorkinguy-terraform-states-backend-demo"
    dynamodb_table = "main-prod-dvorkinguy-terraform-states-backend-demo"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
